services:
  nestjs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs_app
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - postgres
      - mongodb 
    networks:
      - backend_network

  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=Esteban57P
      - POSTGRES_DB=project
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - backend_network

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb-data:/data/db
    networks:
      - backend_network

networks:
  backend_network:
    driver: bridge
